export interface GadgetPref {
  id: string
  section: string
  label: string
  defaultOn: boolean
  rights: string[]
}

export const GADGET_SECTION_LABELS: Record<string, string> = {
  browsing: 'Browsing',
  watchlist: 'Watchlist',
  editing: 'Editing',
  appearance: 'Appearance',
  advanced: 'Advanced',
  maintenance: 'Maintenance',
  test: 'Testing and development',
  'template-gadgets': 'Template gadgets',
  modules: 'Modules',
}

export const GADGETS: GadgetPref[] = [
  { id: 'modrollback', section: 'browsing', label: '(S) After rolling back a user\'s edit, automatically open their contributions page. (Note: Incompatible with the "Show a confirmation prompt when clicking on a rollback link" appearance preference).', defaultOn: false, rights: ['rollback'] },
  { id: 'confirmationRollback-mobile', section: 'browsing', label: '(D) Require confirmation before performing rollback on mobile devices', defaultOn: true, rights: ['rollback'] },
  { id: 'removeAccessKeys', section: 'browsing', label: 'Disable access keys', defaultOn: false, rights: [] },
  { id: 'searchFocus', section: 'browsing', label: 'Focus the cursor in the search bar on loading the Main Page', defaultOn: false, rights: [] },
  { id: 'GoogleTrans', section: 'browsing', label: '(E) (U) GoogleTrans: open a translation popup for the selected text or the word under the cursor when pushing the shift button', defaultOn: false, rights: [] },
  { id: 'ImageAnnotator', section: 'browsing', label: 'ImageAnnotator: view image notes and comments on file description pages', defaultOn: false, rights: [] },
  { id: 'imagelinks', section: 'browsing', label: 'Redirect image links to Commons for files hosted there', defaultOn: false, rights: [] },
  { id: 'Navigation_popups', section: 'browsing', label: 'Navigation popups: article previews and editing functions pop up when hovering over links', defaultOn: false, rights: [] },
  { id: 'exlinks', section: 'browsing', label: 'Open external links in a new tab or window', defaultOn: false, rights: [] },
  { id: 'search-new-tab', section: 'browsing', label: 'Open search results in a new tab or window when holding down the Ctrl key ( discuss)', defaultOn: false, rights: [] },
  { id: 'PrintOptions', section: 'browsing', label: 'Print options: control how pages are printed (for example, remove images or backgrounds)', defaultOn: false, rights: [] },
  { id: 'revisionjumper', section: 'browsing', label: '(S) revisionjumper: quickly navigate between page revisions', defaultOn: false, rights: [] },
  { id: 'Twinkle', section: 'browsing', label: 'Twinkle: add menu buttons to automate common tasks, including: reporting vandalism, warning vandals, requesting deletion or protection, welcoming users, and tagging articles ( preferences)', defaultOn: false, rights: ['autoconfirmed'] },
  { id: 'HideCentralNotice', section: 'browsing', label: 'Suppress display of all CentralNotices (To suppress only certain classes of notices use the Banners option in preferences)', defaultOn: false, rights: [] },
  { id: 'ReferenceTooltips', section: 'browsing', label: '(D) Reference Tooltips: hover over inline citations to see reference information without moving away from the article text (does not work if "Navigation popups" is enabled above)', defaultOn: true, rights: [] },
  { id: 'formWizard', section: 'browsing', label: '(D) FormWizard: a wizard for creating and expanding project pages', defaultOn: true, rights: ['minoredit'] },
  { id: 'Prosesize', section: 'browsing', label: 'Prosesize: add a toolbox link to show the size of and number of words in a page', defaultOn: false, rights: [] },
  { id: 'find-archived-section', section: 'browsing', label: 'find-archived-section: navigate easily to an archived section after following its broken link', defaultOn: false, rights: [] },
  { id: 'geonotice', section: 'watchlist', label: '(D) Geonotice: display notices on your watchlist about events in your region', defaultOn: true, rights: ['viewmywatchlist'] },
  { id: 'watchlist-notice', section: 'watchlist', label: '(D) Display watchlist notices', defaultOn: true, rights: ['viewmywatchlist'] },
  { id: 'WatchlistBase', section: 'watchlist', label: '(D) (This loads the base style for the watchlist. Please do not disable this option.)', defaultOn: true, rights: ['viewmywatchlist'] },
  { id: 'WatchlistGreenIndicators', section: 'watchlist', label: '(D) Display green collapsible arrows and green bullets for changed pages in your watchlist, page history and recent changes (unavailable with the improved Watchlist user interface)', defaultOn: true, rights: ['viewmywatchlist'] },
  { id: 'WatchlistGreenIndicatorsMono', section: 'watchlist', label: '(D) Display green collapsible arrows and green bullets for changed pages in your Watchlist, History and Recent changes (unavailable with the improved Watchlist user interface)', defaultOn: true, rights: ['viewmywatchlist'] },
  { id: 'WatchlistChangesBold', section: 'watchlist', label: 'Display pages on your watchlist that have changed since your last visit in bold (see customizing watchlists for more options)', defaultOn: false, rights: [] },
  { id: 'SubtleUpdatemarker', section: 'watchlist', label: '(D) Subtle update marker: Tone down the "Changed since last visit" indicator on history pages. (By default it renders as a green-filled bar, enabling this gadget changes it to green text.)', defaultOn: true, rights: ['viewmywatchlist'] },
  { id: 'defaultsummaries', section: 'editing', label: 'Add two new dropdown boxes below the edit summary box with some useful default summaries', defaultOn: false, rights: [] },
  { id: 'citations', section: 'editing', label: 'Citation expander: automatically expand and format citations using Citation bot', defaultOn: false, rights: [] },
  { id: 'DotsSyntaxHighlighter', section: 'editing', label: '(S) Syntax highlighter: Alternative to the default coloring of wiki syntax in the edit box (works best in Firefox and works almost all of the time in Chrome and Opera)', defaultOn: false, rights: [] },
  { id: 'HotCat', section: 'editing', label: '(S) HotCat: easily add, remove, and change categories on a page, with name suggestions ( example)', defaultOn: false, rights: ['edit', 'minoredit'] },
  { id: 'wikEdDiff', section: 'editing', label: '(U) wikEdDiff: improved diff view between article versions (not needed if wikEd is used)', defaultOn: false, rights: [] },
  { id: 'ProveIt', section: 'editing', label: '(S) ProveIt is a tool that adds a graphical user interface to find, edit, add and cite references ( demo)', defaultOn: false, rights: [] },
  { id: 'ProveIt-classic', section: 'editing', label: 'ProveIt (classic version) is a tool that adds a graphical user interface to find, edit, add and cite references ( demo). This is the classic, original version of the gadget.', defaultOn: false, rights: [] },
  { id: 'Shortdesc-helper', section: 'editing', label: 'Shortdesc helper: easily add and edit page short descriptions', defaultOn: false, rights: [] },
  { id: 'wikEd', section: 'editing', label: '(U) wikEd: alternative full-featured integrated text editor for Firefox, Safari, and Google Chrome ( documentation)', defaultOn: false, rights: [] },
  { id: 'afchelper', section: 'editing', label: 'AFC Helper Script: easily review Articles for creation submissions (drafts)', defaultOn: false, rights: [] },
  { id: 'charinsert', section: 'editing', label: '(D) CharInsert: add a toolbar under the edit window for quickly inserting wiki markup and special characters ( troubles?)', defaultOn: true, rights: [] },
  { id: 'legacyToolbar', section: 'editing', label: 'Enable the legacy (2006) editing toolbar. This will be overridden by the "Enable the editing toolbar" option in the Editing tab.', defaultOn: false, rights: [] },
  { id: 'refToolbar', section: 'editing', label: '(D) refToolbar: add a "cite" button to the editing toolbar for quick addition of commonly used citation templates', defaultOn: true, rights: [] },
  { id: 'edittop', section: 'appearance', label: 'Add an [edit] link for the lead section of a page', defaultOn: false, rights: [] },
  { id: 'UTCLiveClock', section: 'appearance', label: '(S) Add a clock to the personal toolbar that displays the current time in UTC and provides a link to purge the current page ( documentation)', defaultOn: false, rights: [] },
  { id: 'purgetab', section: 'appearance', label: 'Add a "Purge" option to the top of the page, which purges the page\'s cache', defaultOn: false, rights: [] },
  { id: 'ExternalSearch', section: 'appearance', label: 'Add a selector to the Wikipedia search page allowing the use of external search engines', defaultOn: false, rights: [] },
  { id: 'CollapsibleNav', section: 'appearance', label: 'Allow navigation menus to be collapsed', defaultOn: false, rights: [] },
  { id: 'MenuTabsToggle', section: 'appearance', label: 'Allow toggling between tabs and dropdown menus ( bug reports)', defaultOn: false, rights: [] },
  { id: 'dropdown-menus', section: 'appearance', label: '(S) MoreMenu: add Page and User dropdown menus to the toolbar with links to common tasks, analytic tools and logs', defaultOn: false, rights: [] },
  { id: 'CategoryAboveAll', section: 'appearance', label: 'Place the category box above all other content', defaultOn: false, rights: [] },
  { id: 'addsection-plus', section: 'appearance', label: 'Replace the "new section" tab text with "+"', defaultOn: false, rights: [] },
  { id: 'CommentsInLocalTime', section: 'appearance', label: '(U) Change UTC -based times and dates, such as those used in signatures, to be relative to local time ( documentation)', defaultOn: false, rights: [] },
  { id: 'OldDiff', section: 'appearance', label: 'Display diffs with the old yellow-and-green colors and design', defaultOn: false, rights: [] },
  { id: 'NoAnimations', section: 'appearance', label: 'Disable animations in the interface', defaultOn: false, rights: [] },
  { id: 'disablesuggestions', section: 'appearance', label: 'Disable the suggestions dropdown-lists of the search fields', defaultOn: false, rights: [] },
  { id: 'NoSmallFonts', section: 'appearance', label: 'Disable smaller font sizes of elements such as infoboxes, navboxes and reference lists', defaultOn: false, rights: [] },
  { id: 'topalert', section: 'appearance', label: 'Display a floating alert for new talk page messages', defaultOn: false, rights: [] },
  { id: 'metadata', section: 'appearance', label: 'Display an assessment of an article\'s quality in its page header ( documentation)', defaultOn: false, rights: [] },
  { id: 'JustifyParagraphs', section: 'appearance', label: 'Justify paragraphs', defaultOn: false, rights: [] },
  { id: 'righteditlinks', section: 'appearance', label: 'Move section [edit] links to the right side of the screen', defaultOn: false, rights: [] },
  { id: 'PrettyLog', section: 'appearance', label: 'PrettyLog: format log pages like search results, and add small thumbnails for file uploads', defaultOn: false, rights: [] },
  { id: 'switcher', section: 'appearance', label: '(D) Show radio buttons to switch between views of certain content, such as some maps', defaultOn: true, rights: [] },
  { id: 'SidebarTranslate', section: 'appearance', label: 'SidebarTranslate: display sidebar language links in English', defaultOn: false, rights: [] },
  { id: 'Blackskin', section: 'appearance', label: 'Use a black background with green text', defaultOn: false, rights: [] },
  { id: 'dark-mode-toggle', section: 'appearance', label: 'Dark mode toggle: Enable a toggle for using a light text on dark background color scheme', defaultOn: false, rights: [] },
  { id: 'VectorClassic', section: 'appearance', label: 'Vector classic typography (use only sans-serif in Vector skin)', defaultOn: false, rights: [] },
  { id: 'widensearch', section: 'appearance', label: 'Widen the search box in the Vector skin', defaultOn: false, rights: [] },
  { id: 'DisambiguationLinks', section: 'appearance', label: 'Display links to disambiguation pages in orange', defaultOn: false, rights: [] },
  { id: 'markblocked', section: 'appearance', label: 'Strike out usernames that have been blocked', defaultOn: false, rights: [] },
  { id: 'responsiveContent', section: 'appearance', label: 'Improved appearance for mobile, narrow and wide screens ( documentation)', defaultOn: false, rights: [] },
  { id: 'responsiveContentTimeless', section: 'appearance', label: '(D) Improved appearance for mobile and narrow screens', defaultOn: true, rights: [] },
  { id: 'HideInterwikiSearchResults', section: 'appearance', label: 'Do not show search results for sister projects on the search results page', defaultOn: false, rights: [] },
  { id: 'XTools-ArticleInfo', section: 'appearance', label: 'XTools: dynamically show statistics about a page\'s history under the page heading', defaultOn: false, rights: [] },
  { id: 'remove-sticky-decoration', section: 'appearance', label: 'Remove sticky elements from userpages (see the guidelines on how this works)', defaultOn: false, rights: [] },
  { id: 'InterProjectLinks', section: 'appearance', label: 'InterProjectLinks: Show "In other projects" on articles (using {{ InterProject }}).', defaultOn: false, rights: [] },
  { id: 'ShowMessageNames', section: 'advanced', label: 'Add a toolbox link to reload the current page with the system message names exposed', defaultOn: false, rights: [] },
  { id: 'DebugMode', section: 'advanced', label: 'Add a toolbox link to reload the current page with Resource Loader in debug mode', defaultOn: false, rights: [] },
  { id: 'contribsrange', section: 'advanced', label: 'Allow /16, /24 and /27 – /32 CIDR ranges on Special:Contributions forms, as well as wildcard prefix searches (e.g., "Splark*") ( report issues)', defaultOn: false, rights: [] },
  { id: 'BugStatusUpdate', section: 'advanced', label: 'Enable tracking bugs on Phabricator using the {{ tracked }} template', defaultOn: false, rights: [] },
  { id: 'RTRC', section: 'advanced', label: '(S) Real-Time Recent Changes: patrol recent changes in real-time (unpatrolled filter only works for new pages)', defaultOn: false, rights: [] },
  { id: 'script-installer', section: 'advanced', label: 'Install scripts without having to manually edit JavaScript files ( documentation)', defaultOn: false, rights: [] },
  { id: 'XFDcloser', section: 'maintenance', label: 'XFDcloser: close deletion discussions at XfD venues, including actions to implement closes', defaultOn: false, rights: ['extendedconfirmed'] },
  { id: 'mobile-sidebar', section: 'test', label: 'Mobile sidebar preview: show page in mobile view while browsing the desktop site ( Vector skin only)', defaultOn: false, rights: [] },
  { id: 'addMe', section: 'test', label: '(S) AddMe: endorse or join a project using {{ Probox }}', defaultOn: false, rights: [] },
  { id: 'NewImageThumb', section: 'test', label: 'New image thumb design, and other minor styling tweaks (TOC, categories). Discuss.', defaultOn: false, rights: [] },
  { id: 'StickyTableHeaders', section: 'test', label: 'Make headers of tables display as long as the table is in view, i.e. "sticky" (requires Chrome v91+, Firefox v59+, or Safari)', defaultOn: false, rights: [] },
  { id: 'MobileMaps', section: 'test', label: 'Add map popups to coordinates in the mobile website', defaultOn: false, rights: [] },
  { id: 'ShowJavascriptErrors', section: 'test', label: 'Show an alert when you encounter JavaScript errors', defaultOn: false, rights: [] },
  { id: 'PageDescriptions', section: 'test', label: 'Show page description beneath the page title (not compatible with Page assessments gadget)', defaultOn: false, rights: [] },
  { id: 'autonum', section: 'test', label: 'Auto-number headings: Adds hierarchical outline-style numbering to headers in articles ( documentation)', defaultOn: false, rights: [] },
  { id: 'Vivarium', section: 'template-gadgets', label: '(D) Vivarium: enable interactivity in {{ Conway\'s Game of Life gadget }} template', defaultOn: true, rights: [] },
  { id: 'WikiMiniAtlas', section: 'template-gadgets', label: '(D) WikiMiniAtlas: Popup maps on articles with coordinates', defaultOn: true, rights: [] },
  { id: 'ImageStackPopup', section: 'template-gadgets', label: '(D) Enable viewing stacked images using {{ ImageStackPopup }} template', defaultOn: true, rights: [] },
  { id: 'Calculator', section: 'template-gadgets', label: '(D) Enable interactive calculations on pages using {{ calculator }} template', defaultOn: true, rights: [] },
  { id: 'owidslider', section: 'template-gadgets', label: '(D) Shows a popup dialog with a slider for OWID images', defaultOn: true, rights: [] },
  { id: 'dark-mode', section: 'modules', label: 'Core styling for dark mode gadget (Use the dark mode toggle gadget above to control this feature)', defaultOn: false, rights: [] },
]
