/** Representative interface-language list used on Special:Preferences. */
export const INTERFACE_LANGUAGES = [
  { value: 'en', label: 'en - English' },
  { value: 'en-gb', label: 'en-gb - British English' },
  { value: 'en-ca', label: 'en-ca - Canadian English' },
  { value: 'simple', label: 'simple - Simple English' },
  { value: 'ar', label: 'ar - العربية' },
  { value: 'bn', label: 'bn - বাংলা' },
  { value: 'ca', label: 'ca - català' },
  { value: 'cs', label: 'cs - čeština' },
  { value: 'da', label: 'da - dansk' },
  { value: 'de', label: 'de - Deutsch' },
  { value: 'el', label: 'el - Ελληνικά' },
  { value: 'es', label: 'es - español' },
  { value: 'fa', label: 'fa - فارسی' },
  { value: 'fi', label: 'fi - suomi' },
  { value: 'fr', label: 'fr - français' },
  { value: 'he', label: 'he - עברית' },
  { value: 'hi', label: 'hi - हिन्दी' },
  { value: 'hu', label: 'hu - magyar' },
  { value: 'id', label: 'id - Bahasa Indonesia' },
  { value: 'it', label: 'it - italiano' },
  { value: 'ja', label: 'ja - 日本語' },
  { value: 'ko', label: 'ko - 한국어' },
  { value: 'nl', label: 'nl - Nederlands' },
  { value: 'no', label: 'nb - norsk bokmål' },
  { value: 'pl', label: 'pl - polski' },
  { value: 'pt', label: 'pt - português' },
  { value: 'pt-br', label: 'pt-br - português do Brasil' },
  { value: 'ro', label: 'ro - română' },
  { value: 'ru', label: 'ru - русский' },
  { value: 'sv', label: 'sv - svenska' },
  { value: 'th', label: 'th - ไทย' },
  { value: 'tr', label: 'tr - Türkçe' },
  { value: 'uk', label: 'uk - українська' },
  { value: 'vi', label: 'vi - Tiếng Việt' },
  { value: 'zh', label: 'zh - 中文' },
  { value: 'zh-hans', label: 'zh-hans - 中文（简体）' },
  { value: 'zh-hant', label: 'zh-hant - 中文（繁體）' },
]
